/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ELementos.Glosario;
import ELementos.Termino;
import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ASUS
 */
public class Ver extends javax.swing.JDialog {
    private VerTermino verTermino;
    private Glosario glosario;
    private PrincipalView vistaPrincipal;
    private int estado;
    private int indexRemove;
    private int fila;
    /**
     * Creates new form Ver
     */
    public Ver(PrincipalView vistaPrincipal, boolean modal) {
        super(vistaPrincipal, true);
        this.vistaPrincipal = vistaPrincipal;
        glosario = vistaPrincipal.getGlosario();
        initComponents();
        tablaDatosPricnipal.setVisible(false);
        tablaCategorias.setVisible(false);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 90,90);
        AWTUtilities.setWindowShape(this, forma);        
        setLocationRelativeTo(null);
        actualizarTerminos();
        try {
            glosario.determinarOpcionesVer(this, 0, tablaDatos,0,null);
        } catch (IOException ex) {
            Logger.getLogger(Ver.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ver.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaCategorias = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDatos1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaDatos2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaDatos3 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaDatos5 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaDatos6 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaDatos7 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaDatos4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVerTermino = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        checkGeneral = new javax.swing.JCheckBox();
        checkCategoria = new javax.swing.JCheckBox();
        tablaDatosPricnipal = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCategorias.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setFocusable(false);
        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tablaDatos1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablaDatos1.setForeground(new java.awt.Color(102, 102, 102));
        tablaDatos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre termino:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos1.setToolTipText("");
        tablaDatos1.setRowHeight(30);
        tablaDatos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatos1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaDatos1);

        tablaCategorias.addTab("tab1", jScrollPane3);

        jScrollPane4.setFocusable(false);
        jScrollPane4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tablaDatos2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablaDatos2.setForeground(new java.awt.Color(102, 102, 102));
        tablaDatos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre termino:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos2.setToolTipText("");
        tablaDatos2.setRowHeight(30);
        tablaDatos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatos2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaDatos2);

        tablaCategorias.addTab("tab1", jScrollPane4);

        jScrollPane5.setFocusable(false);
        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tablaDatos3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablaDatos3.setForeground(new java.awt.Color(102, 102, 102));
        tablaDatos3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre termino:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos3.setToolTipText("");
        tablaDatos3.setRowHeight(30);
        tablaDatos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatos3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablaDatos3);

        tablaCategorias.addTab("tab1", jScrollPane5);

        jScrollPane7.setFocusable(false);
        jScrollPane7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tablaDatos5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablaDatos5.setForeground(new java.awt.Color(102, 102, 102));
        tablaDatos5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre termino:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos5.setToolTipText("");
        tablaDatos5.setRowHeight(30);
        tablaDatos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatos5MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablaDatos5);

        tablaCategorias.addTab("tab1", jScrollPane7);

        jScrollPane8.setFocusable(false);
        jScrollPane8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tablaDatos6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablaDatos6.setForeground(new java.awt.Color(102, 102, 102));
        tablaDatos6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre termino:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos6.setToolTipText("");
        tablaDatos6.setRowHeight(30);
        tablaDatos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatos6MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tablaDatos6);

        tablaCategorias.addTab("tab1", jScrollPane8);

        jScrollPane9.setFocusable(false);
        jScrollPane9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tablaDatos7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablaDatos7.setForeground(new java.awt.Color(102, 102, 102));
        tablaDatos7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre termino:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos7.setToolTipText("");
        tablaDatos7.setRowHeight(30);
        tablaDatos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatos7MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tablaDatos7);

        tablaCategorias.addTab("tab1", jScrollPane9);

        jScrollPane6.setFocusable(false);
        jScrollPane6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tablaDatos4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablaDatos4.setForeground(new java.awt.Color(102, 102, 102));
        tablaDatos4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre termino:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos4.setToolTipText("");
        tablaDatos4.setRowHeight(30);
        tablaDatos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatos4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tablaDatos4);

        tablaCategorias.addTab("tab1", jScrollPane6);

        getContentPane().add(tablaCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 260, 310));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Diccionario Técnico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 240, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 40, 50));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Volver");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 330, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img_416864 (1).png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 60, 70));

        btnVerTermino.setText("Ver");
        btnVerTermino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVerTermino.setContentAreaFilled(false);
        btnVerTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTerminoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 100, 40));

        txtBusqueda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Busca");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, 40));

        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("el termino:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, 40));

        checkGeneral.setBackground(new java.awt.Color(255, 255, 255));
        checkGeneral.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkGeneral.setText("Ver todos los terminos");
        checkGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGeneralActionPerformed(evt);
            }
        });
        getContentPane().add(checkGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        checkCategoria.setBackground(new java.awt.Color(255, 255, 255));
        checkCategoria.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkCategoria.setText("Ver por Categorias");
        checkCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(checkCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        tablaDatosPricnipal.setFocusable(false);
        tablaDatosPricnipal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tablaDatos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablaDatos.setForeground(new java.awt.Color(102, 102, 102));
        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre termino:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos.setToolTipText("");
        tablaDatos.setRowHeight(30);
        tablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosMouseClicked(evt);
            }
        });
        tablaDatosPricnipal.setViewportView(tablaDatos);

        getContentPane().add(tablaDatosPricnipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, 262));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plantillaIphone (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        estado = 1;
        try {
            glosario.determinarOpcionesVer(this, estado, tablaDatos,indexRemove,null);  
            actualizarTerminos();
        } catch (IOException ex) {
            Logger.getLogger(Ver.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ver.class.getName()).log(Level.SEVERE, null, ex);
        } catch(IndexOutOfBoundsException iobe) {
            JOptionPane.showMessageDialog(null, "No hay ningún término para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMouseClicked
        indexRemove = tablaDatos.rowAtPoint(evt.getPoint());
        
    }//GEN-LAST:event_tablaDatosMouseClicked

    private void btnVerTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTerminoActionPerformed
        estado = 2;
        try { 
            actualizarTerminos();
            Termino termino = glosario.determinarOpcionesVer(this,estado,tablaDatos,indexRemove,null);
            dispose();
            VerTermino dialogoVerTermino = new VerTermino(vistaPrincipal, true, termino);
        } catch (IOException ex) {
            Logger.getLogger(Ver.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ver.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IndexOutOfBoundsException iobe) {
            JOptionPane.showMessageDialog(null, "No hay ningún término para ver.");
        }
    }//GEN-LAST:event_btnVerTerminoActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        estado = 3;
        try { 
            Termino termino = glosario.determinarOpcionesVer(this,estado,tablaDatos,indexRemove,txtBusqueda.getText());
            VerTermino dialogoVerTermino = new VerTermino(vistaPrincipal, true, termino);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(Ver.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ver.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IndexOutOfBoundsException iobe) {
            JOptionPane.showMessageDialog(null, "No hay ningún término para ver.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaDatos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDatos1MouseClicked

    private void tablaDatos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatos2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDatos2MouseClicked

    private void tablaDatos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatos3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDatos3MouseClicked

    private void tablaDatos4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatos4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDatos4MouseClicked

    private void tablaDatos5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatos5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDatos5MouseClicked

    private void tablaDatos6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatos6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDatos6MouseClicked

    private void tablaDatos7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatos7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDatos7MouseClicked

    private void checkCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCategoriaActionPerformed
        checkGeneral.setSelected(false);
        actualizarTerminos();
        
    }//GEN-LAST:event_checkCategoriaActionPerformed

    private void checkGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGeneralActionPerformed
        checkCategoria.setSelected(false);
        actualizarTerminos();        
    }//GEN-LAST:event_checkGeneralActionPerformed
    public void actualizarTerminos(){
        if(checkCategoria.isSelected()){
            tablaCategorias.setVisible(true);
            tablaDatosPricnipal.setVisible(false);
        }
        if(checkGeneral.isSelected()){
            tablaDatosPricnipal.setVisible(true);
            tablaCategorias.setVisible(false);
        }
        if((!checkGeneral.isSelected()& !checkCategoria.isSelected())){
            tablaCategorias.setVisible(false);
            tablaDatosPricnipal.setVisible(false);
        }
    }
    public JTable getTablaDatos() {
        return tablaDatos;
    }

    public void setTablaDatos(JTable tablaDatos) {
        this.tablaDatos = tablaDatos;
    }

    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVerTermino;
    private javax.swing.JCheckBox checkCategoria;
    private javax.swing.JCheckBox checkGeneral;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane tablaCategorias;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTable tablaDatos1;
    private javax.swing.JTable tablaDatos2;
    private javax.swing.JTable tablaDatos3;
    private javax.swing.JTable tablaDatos4;
    private javax.swing.JTable tablaDatos5;
    private javax.swing.JTable tablaDatos6;
    private javax.swing.JTable tablaDatos7;
    private javax.swing.JScrollPane tablaDatosPricnipal;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
